### ISSUE TITLE
Do we want to have badges below the package level?

### ISSUE THREAD

**Issue by sckott** [getwilds/badges#1]
@seankross 

So we did talk about possibly having an R package to do badge things. however, the only justifiable reason I can think to do that is if we want to use statuses on functions/classes/etc. below the package level, then an R package like https://github.com/r-lib/lifecycle/ really makes sense. I imagine we revisit this later if we thinks its needed? We could decide whenever that we should have function/class level statuses, but my gut feeling is we're not at that point yet

Thoughts?

**Comment by seankross** [comment]
I agree we're not at that point yet, the badges only make sense on the repository level for now.

**Comment by sckott** [comment]
Okay, closing this for now. we can revisit if we go below pkg level
