### ISSUE TITLE
Point people to this repo or a rendered gh-pages site?

### ISSUE THREAD

**Issue by sckott** [getwilds/badges#2]
@seankross Should we point people to the readme of this repo? Or to a rendered gh-pages page? 

That is, folllowing the repostatus or lifecycle pattern, clicking on one of our badges would bring the user to some site, which could be whatever. I'm guessing we should have people land on a gh-pages page?

**Comment by sckott** [comment]
page at https://getwilds.github.io/badges/

**Comment by seankross** [comment]
I agree I would send people to the site.

**Comment by sckott** [comment]
cool, done
