### ISSUE TITLE
Custom DaSL badges

### ISSUE THREAD

**Issue by sckott** [getwilds/badges#3]
@seankross Do we want any custom badges? If we do not, then we may not need this repo and can just use the badges and point to repostatus. But if we do want some custom badges, what custom badges do we want?  

- open to feedback before shipping
- what else?

Even if we don't want custom badges we could still have this repo to document any further guidance we want to give our community around our use of badges

**Comment by seankross** [comment]
I feel like each badge should answer these questions:

1. Is this useable?
2. Can I get support?
3. Are you open to feedback?
4. Is the API stable?

So then I see the badges as follows (these don't have to be the names):

- WIP: Not useable, no support, not open to feedback, unstable API.
- Experimental: useable, some support, not open to feedback, unstable API.
- Draft: useable, some support, open to feedback, unstable API.
- Stable: useable, full support, open to feedback, stable API.
- Deprecated: useable as of a fixed, past date, no support, not open to feedback, stable API as of a fixed, past date.

**Comment by seankross** [comment]
Do think these leaves anything out? Should we go with different names?

**Comment by sckott** [comment]
I like this reframing! 

I think the flow from WIP to Draft could be better wrt the names. That is, WIP -> Experimental -> Draft isn't intuitive. Maybe:

- Change WIP to Concept, and
- I'm kind of side-eyeing Draft. It's okay, but there's not anything perfect to improve up on it. Maybe Prototype? 

I can't think of any additional statuses

**Comment by seankross** [comment]
Agree change WIP to Concept. I like Prototype instead of Draft, let's do it.

**Comment by sckott** [comment]
will do
