### ISSUE TITLE
Use badges niceties

### ISSUE THREAD

**Issue by sckott** [getwilds/badges#4]
It would be great to have a copy to clipboard button for badge text. We can poke around for javascriopt to use to do it, or possibly even use quarto which i know has that built in already

**Comment by seankross** [comment]
Love this idea, I think copy clipboard has a canonical JS API these days.

**Comment by sckott** [comment]
Cool. Will try JS in jekyll, and quarto and see which is better

**Comment by sckott** [comment]
Working but needs some clean up:

- [x] what button colors?
- [x] better layout of the 5 statuses and 3 markup options
- ~~little icon on the buttons that changes after you click to copy? stretch goal~~ (nah, there isn't one for rest, so forget about it)
