### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by sckott** [getwilds/badges#5]
- Right now I only have the active badge copied from repostatus, but can copy over more
- What text do we want to have on the left side? Right now it says `repo status`. Do we want to change that to something else? 
- Colors of the badges. They seem okay to me, but we can change them

**Comment by sckott** [comment]
Any feelings on the above @seankross ?

**Comment by seankross** [comment]
> What text do we want to have on the left side? Right now it says repo status. Do we want to change that to something else?

I don't mind `repo status` but I'm open to suggestions. 

> Colors

Are okay with me.

**Comment by sckott** [comment]
i think repo status is good. 

I changed the colors of the buttons to click to get the badge text, but the badge colors are still the same.
